apiVersion: v1
kind: ConfigMap        #holds Kubernetes config data
metadata:
  name: cnas-app-config
  labels:
    app.kubernetes.io/name: cnas-app-config
data:
  DB_HOST: cnas-mysql
  DB_PORT: "3306"
  DB_NAME: mydb
  APP_ENV: production


/*What is this file for?
This file creates a Kubernetes resource called a ConfigMap.

In Cloud Native architecture, a fundamental rule is to separate your configuration settings from your actual application code. The purpose of this file is to store these non-secret configuration settings (like database names and environment states) in one central place. By keeping these settings separate, you can run the exact same application code in different environments (like a testing server or a live production server) simply by changing this configuration file, without ever modifying the code itself.*/