apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnas-deployer
  namespace: cnas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnas-deployer
  namespace: cnas
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnas-deployer
  namespace: cnas
subjects:
  - kind: ServiceAccount
    name: cnas-deployer
    namespace: cnas
roleRef:
  kind: Role
  name: cnas-deployer
  apiGroup: rbac.authorization.k8s.io
