apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnas

commonLabels:
  app.kubernetes.io/part-of: cnas-assignment

resources:
  - namespace.yaml
  - configmap.yaml
  - secret-template.yaml
  - local-storage.yaml
  - mysql-initdb-configmap.yaml
  - mysql-service.yaml
  - mysql-statefulset.yaml
  - web-serviceaccount.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
