apiVersion: v1
kind: Secret
metadata:
  name: cnas-db-secret
  labels:
    app.kubernetes.io/name: cnas-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "TODO_CHANGE_ME_ROOT_PASSWORD"
  MYSQL_USER: "cnas_user"
  MYSQL_PASSWORD: "TODO_CHANGE_ME_APP_PASSWORD"
  DB_USER: "cnas_user"
  DB_PASSWORD: "TODO_CHANGE_ME_APP_PASSWORD"

