apiVersion: v1
kind: Secret
metadata:
  name: cnas-db-secret
  labels:
    app.kubernetes.io/name: cnas-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass"
  MYSQL_USER: "cnas_user"
  MYSQL_PASSWORD: "sqlpass"
  DB_USER: "cnas_user"
  DB_PASSWORD: "sqlpass"
