apiVersion: v1
kind: ServiceAccount
# ServiceAccount = identity/permissions for the pod (like a user account)
metadata:
  name: cnas-web
  labels:
    app.kubernetes.io/name: cnas-web
    app.kubernetes.io/component: web
automountServiceAccountToken: false
# Don't give pod credentials. PHP app doesn't need to talk to Kubernetes API, so safer to not give it access.

