services:
  app:
    build: ./app
    image: cnas-php-mysql:local #tag the deployment expects
    container_name: php_web
    ports:
      - "9090:8080"
    user: "1000:1000"
    mem_limit: 256m
    cpus: 0.5
    volumes:
      - ./app:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: mydb
      DB_USER: cnas_user
      DB_PASSWORD: apppass
    depends_on:
      - db
    networks: [backend]
  db: 
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: cnas_user
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: [backend]
networks:
    backend:
      driver: bridge
